In [1]:
import pandas as pd

#import Pandas as pd#

In [2]:
df = pd.read_csv('netflix_titles.csv')

#make sure file is in same location as your jupyter notebook file#

In [3]:
print (df)

#print data frame#

       show_id     type                                        title  \
0     81145628    Movie      Norm of the North: King Sized Adventure
1     80117401    Movie                   Jandino: Whatever it Takes
2     70234439  TV Show                           Transformers Prime
3     80058654  TV Show             Transformers: Robots in Disguise
4     80125979    Movie                                 #realityhigh
...        ...      ...                                          ...
6229  80000063  TV Show                                 Red vs. Blue
6230  70286564  TV Show                                        Maron
6231  80116008    Movie       Little Baby Bum: Nursery Rhyme Friends
6232  70281022  TV Show  A Young Doctor's Notebook and Other Stories
6233  70153404  TV Show                                      Friends

                      director  \
0     Richard Finn, Tim Maltby
1                          NaN
2                          NaN
3                          NaN
4             Fernando Lebrija
...                        ...
6229                       NaN
6230                       NaN
6231                       NaN
6232                       NaN
6233                       NaN

                                                   cast  \
0     Alan Marriott, Andrew Toth, Brian Dobson, Cole...
1                                      Jandino Asporaat
2     Peter Cullen, Sumalee Montano, Frank Welker, J...
3     Will Friedle, Darren Criss, Constance Zimmer, ...
4     Nesta Cooper, Kate Walsh, John Michael Higgins...
...                                                 ...
6229  Burnie Burns, Jason Salda√±a, Gustavo Sorola, G...
6230  Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...
6231                                                NaN
6232  Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...
6233  Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...

                                       country         date_added  \
0     United States, India, South Korea, China  September 9, 2019
1                               United Kingdom  September 9, 2016
2                                United States  September 8, 2018
3                                United States  September 8, 2018
4                                United States  September 8, 2017
...                                        ...                ...
6229                             United States                NaN
6230                             United States                NaN
6231                                       NaN                NaN
6232                            United Kingdom                NaN
6233                             United States                NaN

      release_year    rating    duration  \
0             2019     TV-PG      90 min
1             2016     TV-MA      94 min
2             2013  TV-Y7-FV    1 Season
3             2016     TV-Y7    1 Season
4             2017     TV-14      99 min
...            ...       ...         ...
6229          2015        NR  13 Seasons
6230          2016     TV-MA   4 Seasons
6231          2016       NaN      60 min
6232          2013     TV-MA   2 Seasons
6233          2003     TV-14  10 Seasons

                                              listed_in  \
0                    Children & Family Movies, Comedies
1                                       Stand-Up Comedy
2                                              Kids' TV
3                                              Kids' TV
4                                              Comedies
...                                                 ...
6229  TV Action & Adventure, TV Comedies, TV Sci-Fi ...
6230                                        TV Comedies
6231                                             Movies
6232           British TV Shows, TV Comedies, TV Dramas
6233                     Classic & Cult TV, TV Comedies

                                            description
0     Before planning an awesome wedding for his gra...
1     Jandino Asporaat riffs on the challenges of ra...
2     With the help of three human allies, the Autob...
3     When a prison ship crash unleashes hundreds of...
4     When nerdy high schooler Dani finally attracts...
...                                                 ...
6229  This parody of first-person shooter games, mil...
6230  Marc Maron stars as Marc Maron, who interviews...
6231  Nursery rhymes and original music for children...
6232  Set during the Russian Revolution, this comic ...
6233  This hit sitcom follows the merry misadventure...

[6234 rows x 12 columns]

In [5]:
df.head()

#print first 4 rows of data frame#

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [7]:
df = df.dropna()

#drop all rows with NaN#

In [8]:
print(df)

       show_id     type                                    title  \
0     81145628    Movie  Norm of the North: King Sized Adventure
4     80125979    Movie                             #realityhigh
6     70304989    Movie                                 Automata
7     80164077    Movie       Fabrizio Copano: Solo pienso en mi
9     70304990    Movie                              Good People
...        ...      ...                                      ...
6142  80063224  TV Show            The Great British Baking Show
6158  80164216  TV Show  Miraculous: Tales of Ladybug & Cat Noir
6167  80115328  TV Show                             Sacred Games
6182  80176842  TV Show                         Men on a Mission
6213  80126599  TV Show                         Leyla and Mecnun

                                  director  \
0                 Richard Finn, Tim Maltby
4                         Fernando Lebrija
6                              Gabe Ib√°√±ez
7          Rodrigo Toro, Francisco Schultz
9                        Henrik Ruben Genz
...                                    ...
6142                       Andy Devonshire
6158                         Thomas Astruc
6167  Vikramaditya Motwane, Anurag Kashyap
6182                            Jung-ah Im
6213                             Onur √únl√º

                                                   cast  \
0     Alan Marriott, Andrew Toth, Brian Dobson, Cole...
4     Nesta Cooper, Kate Walsh, John Michael Higgins...
6     Antonio Banderas, Dylan McDermott, Melanie Gri...
7                                       Fabrizio Copano
9     James Franco, Kate Hudson, Tom Wilkinson, Omar...
...                                                 ...
6142  Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...
6158  Cristina Vee, Bryce Papenbrook, Keith Silverst...
6167  Saif Ali Khan, Nawazuddin Siddiqui, Radhika Ap...
6182  Ho-dong Kang, Soo-geun Lee, Sang-min Lee, Youn...
6213  Ali Atay, Melis Birkan, Serkan Keskin, Ahmet M...

                                             country         date_added  \
0           United States, India, South Korea, China  September 9, 2019
4                                      United States  September 8, 2017
6             Bulgaria, United States, Spain, Canada  September 8, 2017
7                                              Chile  September 8, 2017
9     United States, United Kingdom, Denmark, Sweden  September 8, 2017
...                                              ...                ...
6142                                  United Kingdom    August 30, 2019
6158                      France, South Korea, Japan     August 2, 2019
6167                            India, United States    August 15, 2019
6182                                     South Korea      April 9, 2019
6213                                          Turkey     April 15, 2017

      release_year rating   duration  \
0             2019  TV-PG     90 min
4             2017  TV-14     99 min
6             2014      R    110 min
7             2017  TV-MA     60 min
9             2014      R     90 min
...            ...    ...        ...
6142          2019  TV-PG  7 Seasons
6158          2018  TV-Y7  4 Seasons
6167          2019  TV-MA  2 Seasons
6182          2019  TV-14  4 Seasons
6213          2014  TV-PG  3 Seasons

                                              listed_in  \
0                    Children & Family Movies, Comedies
4                                              Comedies
6     International Movies, Sci-Fi & Fantasy, Thrillers
7                                       Stand-Up Comedy
9                         Action & Adventure, Thrillers
...                                                 ...
6142                       British TV Shows, Reality TV
6158                    Kids' TV, TV Action & Adventure
6167  Crime TV Shows, International TV Shows, TV Dramas
6182  International TV Shows, Korean TV Shows, Stand...
6213  International TV Shows, Romantic TV Shows, TV ...

                                            description
0     Before planning an awesome wedding for his gra...
4     When nerdy high schooler Dani finally attracts...
6     In a dystopian future, an insurance adjuster f...
7     Fabrizio Copano takes audience participation t...
9     A struggling couple can't believe their luck w...
...                                                 ...
6142  A talented batch of amateur bakers face off in...
6158  When Paris is in peril, Marinette becomes Lady...
6167  A link in their pasts leads an honest cop to a...
6182  Male celebs play make-believe as high schooler...
6213  Destiny brings Mecnun and Leyla together as ne...

[3774 rows x 12 columns]

In [10]:
Netflix_Titles = 'Netflix_Titles.xlsx' 

#define .xlsx location#

In [11]:
df.to_excel(Netflix_Titles)

#upload df to excel#